### ISSUE TITLE
Is it possible to translate a "sub-attribute" ?

### ISSUE THREAD

**Issue by SaintTDI** [PiotrMachowski/Home-Assistant-custom-components-Custom-Templates#22]
Hi!
amazing this integration! thank you so much!

I was wondering if it works even with a "sub-attribute". I have the "weather.forecast_casa" integration with these attributes:

```yaml
temperature: 12.3
dew_point: 9.8
temperature_unit: °C
humidity: 84
cloud_coverage: 100
pressure: 1020.9
pressure_unit: hPa
wind_bearing: 359.7
wind_speed: 6.5
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast: 
- **condition: cloudy**
  datetime: '2024-02-16T11:00:00+00:00'
  wind_bearing: 359.7
  temperature: 12.3
  templow: 9.7
  wind_speed: 7.2
  precipitation: 0
  humidity: 84
- condition: sunny
  datetime: '2024-02-17T11:00:00+00:00'
  wind_bearing: 15.2
  temperature: 17.8
  templow: 5.6
  wind_speed: 12.6
  precipitation: 0
  humidity: 62
- condition: sunny
  datetime: '2024-02-18T11:00:00+00:00'
  wind_bearing: 77.9
  temperature: 17.4
  templow: 5.3
  wind_speed: 12.6
  precipitation: 0
  humidity: 67
- condition: cloudy
  datetime: '2024-02-19T11:00:00+00:00'
  wind_bearing: 173.4
  temperature: 14.1
  templow: 5.9
  wind_speed: 11.9
  precipitation: 0.4
  humidity: 76
- condition: partlycloudy
  datetime: '2024-02-20T11:00:00+00:00'
  wind_bearing: 0.1
  temperature: 16.7
  templow: 5.3
  wind_speed: 18
  precipitation: 0.1
  humidity: 57
- condition: sunny
  datetime: '2024-02-21T11:00:00+00:00'
  wind_bearing: 179.3
  temperature: 14.6
  templow: 3
  wind_speed: 12.2
  precipitation: 0
  humidity: 64

attribution: Weather forecast from met.no, delivered by the Norwegian Meteorological Institute.
friendly_name: Forecast FrustyHome
supported_features: 3
```

And how you can see the bold "condition" is under the first "forecast". If I use this statement:

`{{ state_attr('weather.forecast_casa', 'forecast')[0].condition }}`

I have "cloudy" as an output... how could I use your integration to translate it? I tried with :

`test: {{ ct_state_attr_translated("weather.forecast_casa", "forecast[0].condition", "en") }}`

but the output is "None"

Is it possible to use your integration to translate this "sub-attribute" (I don't know how to call it :D ) ?

Thanks!
